pipeline{
    agent any
    environment {
        PATH = "$PATH:'C:/Program Files/apache-maven-3.8.6/bin'"
    }
    stages{
       stage('GetCode'){
            steps{
                git 'https://github.com/Geovany12345/Hotel_Los_Juanes.git'
            }
         }        
       stage('Build'){
            steps{
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
//    def scannerHome = tool 'sonar-scanner';
        steps{
        withSonarQubeEnv('sonar-scanner') { 
        // If you have configured more than one global server connection, you can specify its name
//      sh "${scannerHome}/bin/sonar-scanner"
        sh "mvn sonar:sonar"
    }
        }
        }
       
    }
}

//hola mundo hello