pipeline{
    agent any
    environment {
        PATH = "$PATH:'C:/Program Files/apache-maven-3.8.6/bin'"
        SONARQUBE_SCANNER_PARAMS = "${WORKSPACE}/sonar-project.properties"
    }
    stages{
        stage('GetCode'){
            steps{
                git 'https://github.com/Geovany12345/Hotel_Los_Juanes.git'
            }
        }        
        stage('Build'){
            steps{
                sh 'mvn clean package'
            }
        }
        stage('SonarQube analysis') {
            steps{
                withSonarQubeEnv('sonar-scanner') { 
                    sh "mvn sonar:sonar"
                }
            }
        }
    }
}
